Repository EnigmaVSSUT/Induction-2025, pull requests merged in 2025-04, with the labels that each got.

#1 Remit's first commit
  Open_Source/Task/Remit_Patra/README.md
Labels: awesome, approved

#2 First commit
  Open_Source/Task/Sambhav_Shadangi/README.md
Labels: awesome, approved

#3 gouravKJ-TASK1
  Open_Source/Task/Gourav-KJ/README.md
Labels: awesome, approved

#4 Assignment-1 ITP : Subhashree Sahu
  Open_Source/Task/Subhashree Sahu/README.md
Labels: approved

#5 Vipul Krishna Gahir Info file
  Open_Source/Task/Vipul_Krishna_Gahir/README.md
Labels: awesome, approved

#6 Added details
  Open_Source/Task/Yograj_Patel/README.md
Labels: awesome, approved

#10 DONE BY MADHU SAILESH
  Open_Source/Task/Madhu_Sailesh/README.md
Labels: approved

#11 Completed Open Source Task
  Open_Source/Task/Subham_kumar_Giri/README.md
Labels: awesome, approved

#12 COMPLETED open source task
  Open_Source/Task/Biswajit Baliarsingh/README.md
Labels: approved

#13 Git Bash Task completed
  Open_Source/Task/Abhijit_Sahu/README.md
Labels: awesome, approved

#14 Bikash Added Task
  Open_Source/Task/Bikash_Ranjan_Sahoo/README.md
Labels: approved

#16 Completed Open Source Task
  Open_Source/Task/aditya-hrudaya-sahoo/README.md
Labels: awesome, approved

#17 COMPLETED OPEN SOURCE TASK
  Open_Source/Task/PRATIK KUMAR BEHERA/README.md
Labels: awesome, approved

#18 first commit
  Open_Source/Task/ankitanaik/README.md
Labels: awesome, approved

#22 Task Completed
  Open_Source/Task/Suman Rani Sabat/README.md
Labels: awesome, approved

#23 Completed Open Source Task
  Open_Source/Task/SOUMYA_RANJAN_BHOL/README.md
Labels: approved

#24 COMPLETED OPEN SOURCE TASK
  Open_Source/Task/SUBHAM_TRIPATHY/README.md
Labels: approved

#26 Completed open source task
  Open_Source/Task/Subhran Samuel Kujur/README.md
Labels: approved

#28 Completed Open Source Task
  Open_Source/Task/Aryaman_Singh/README.md
Labels: approved

#29 Added a new README.md file
  Open_Source/Task/Anushree_Mohanty/README.md
Labels: awesome, approved

#30 Task 1 completed
  Open_Source/Task/Vidyoshah_Behera/README.md
Labels: approved

#31 Completed Open Source Task
  Open_Source/Task/sameer_raja/README.md
Labels: approved

#33 Done by T Prem
  Open_Source/Task/T Prem/README.md
Labels: approved

#34 task 1 completed
  Open_Source/Task/Debasish/README.md
Labels: approved

#35 completed open source task
  Open_Source/Task/Gourav_kumar_behera/README.md
Labels: approved

#37 Completed Open Source Task
  Open_Source/Task/Debasmita_raut/README.md
Labels: approved

#38 Added README.md for Aradhya Rath
  Open_Source/Task/Aradhya Rath/README.md
Labels: approved

#39 Completed Open Source Task
  Open_Source/Task/Piyush_Mishra/README.md
Labels: approved

#40 my introduction
  Open_Source/Task/SoumyaRanjanBehera/README.md
Labels: approved

#43 Ashutosh's first commit
  Open_Source/Task/Ashutosh_Biswal/README.md
Labels: approved

#46 Completed Open Source Task
  Open_Source/Task/Aman_Kumar/README.md
Labels: approved

#47 completed open source task
  Open_Source/Task/Priti_Prasanna_Sethi/README.md
Labels: approved

#48 Task-1 : Shaswat H
  Open_Source/Task/Shaswat_Ranjan_Hota/README.md
Labels: approved

#50 Open Source Task Completed
  Open_Source/Task/Satyajit_Swain/README.md
Labels: awesome, approved

#53 Task 1 done
  Open_Source/Task_1/Bhabana_Agrawal/README.md
Labels: approved

#55 completed open source task
  Open_Source/Task/Pralaya Sahoo/README.md
Labels: approved

#57 Completed Open Source Task
  Open_Source/Task/Vysyaraju_Hansuja/README.md
Labels: approved

#58 added itp task 1 by sai
  Open_Source/Task/Sai_bag/README.md
Labels: approved

#59 completed open source task
  Open_Source/Task/Swagat SM/README.md
Labels: approved

#60 Completed Open Source Task
  Open_Source/Task/Susama_Suraj_Singh/README.md
Labels: approved

#62 Completed Open source task
  Open_Source/Task/Subha Sourabha Sahu/README.md
Labels: approved

#63 SUCCESS
  Open_Source/Task/Muzammil_Akhtar/README.md
Labels: approved

#66 sidhartha
  Open_Source/Task/sidharth_kumar_nayak/README.md
Labels: approved

#69 added readme file
  Open_Source/Task/chinmaya sa/readme.md
Labels: approved

#70 Completed Open Source Task
  Open_Source/Task/Sandeep Kumar Sahu/README.md
Labels: approved

#73 Completed Open Source Task -Adarsh Raj
  Open_Source/Task/Adarsh_Raj/README.md
Labels: approved

#75 Completed Open Source Task
  Open_Source/Task/AMISHA_AMAT/README.md
Labels: awesome, approved

#76 Task-1 SRJ
  Open_Source/Task/SRJ/README.md
Labels: approved

#77 Add Natasha sahu README.md file
  Open_Source/Task/Natasha sahu/README.md
Labels: approved

#78 add Namita Naik README.md folder
  Open_Source/Task/Namita Naik/README.md
Labels: approved

#79 added file
  Open_Source/Task/SASWAT-MOHANTY/README.md
Labels: approved

#80 add Bhagabati Rout
  Open_Source/Task/Bhagabati Rout/README.md
Labels: approved

#81 add shreeya
  Open_Source/Task/Shreeya Dora/README.md
Labels: approved

#82 Completed open source task
  Open_Source/Task/Anwesha_sahu/README.md
Labels: approved

#83 add kajal file
  Open_Source/Task/Kajal Mohapatra/README.md
Labels: approved

#85 task1_Aurodeepa
  Open_Source/Task/Aurodeepa_Senapati/README.md
Labels: approved

#86 sayedasaba09
  Open_Source/Task/Sayedasaba09/README.md
Labels: approved

#87 Completed Open Source Task
  Open_Source/Task/Sabyasachee_Sahoo/README.md
Labels: approved

#88 completed open source code
  Open_Source/Task/Arpan/README.md
Labels: approved

#89 task completed
  Open_Source/Task/BHAKTI CHARAN BEHERA/README.md
Labels: approved

#91 added Subhalaxmi files
  Open_Source/Task/Subhalaxmi Naik/README.md
Labels: approved

#94 done by jashosna
  Open_Source/Task/Jashosna/README.md
Labels: approved

#95 Completed Open Source Task
  Open_Source/Task/Rabindra_Dash/README.md
Labels: approved

#97 task#1 complete
  Open_Source/Task/bharati task-1/README.md
Labels: approved

#100 Aryan_Rajguru
  Open_Source/Task/AryanRajguru-18/README.md
Labels: approved

#102 Task 1
  Open_Source/Task/Monalisha Nayak/README.md
Labels: approved

#103 Task Completed
  Open_Source/Task/Prateek_Kumar_Hota/README.md
Labels: approved

#104 Completed Open Source Task
  Open_Source/Task/Deepshikha/README.md
Labels: awesome, approved

#108 completed Task
  Open_Source/Task/Debasish_pradhan/README.md
Labels: approved

#109 Completed Open Source Task
  Open_Source/Task/Niranjan_Mahanta/README.md
Labels: approved

#110 OPEN SOURCE TASK COMPLETED
  Open_Source/Task/Shubham_Sethi/README.md
Labels: approved

#112 Completed Open Source Task
  Open_Source/Task/Rudrakant Sahoo/README.md
Labels: approved

#113 Completed Open Source Task
  Open_Source/Task/Abhijeet_Nanda/README.md
Labels: approved

#115 Added Charchit profile and README.md in Task folder
  Open_Source/Task/Charchit/README.md
Labels: approved

#116 Task 1 Sourav Naik
  Open_Source/Task/Sourav_Naik/Readme.md
Labels: approved

#118 Open Source Task Completed
  Open_Source/Task/Sai_Debadutta_Sethy/README.md
Labels: awesome, approved

#119 Completed Open Source Task
  Open_Source/Task/NITISH/README.md
Labels: approved

#120 task 1 Abhijeet
  Open_Source/Task/Ch_Abhijeet_Achary/README.md
Labels: approved

#121 Open Source Task Completed
  Open_Source/Task/Debendra_Barik/README.md
Labels: approved

#122 My intro
  Open_Source/Task/Subham_kumar_rana/README.md
Labels: approved

#123 Completed Open Source Task
  Open_Source/Task/Karra Harshita/README.md
Labels: approved

#124 completed open source task
  Open_Source/Task/Swati Srujanika Badajena/README.md
Labels: approved

#125 Open source task completed
  Open_Source/Task/suhani sabat/README.md
Labels: approved

#126 add readme file
  Open_Source/Task/Aditi Saraph/README.md
Labels: approved

#130 completed open source task
  Open_Source/Task/Suraj kumar sahu/README.md
Labels: approved

#132 Completed Open Source Task
  Open_Source/Task/Abhishek_Acharya/README.md
Labels: approved

#133 # Task_1
  Open_Source/Task/Om_Prakash_Bisoi/README.md
Labels: approved

#134 suvam's assignment
  Open_Source/Task/Suvam S Parida/README.md
Labels: awesome, approved

#137 Create readme.md
  Open_Source/Task/Shruti/readme.md
Labels: approved

#138 Completed Task-1 [Sampark Sagar Barik]
  Open_Source/Task/Sampark_Sagar_Barik/README.md
Labels: approved

#140 Completed task-1 [Rounak Senapati]
  Open_Source/Task/Rounak_Senapati/README.md
Labels: approved

#142 Priyabrata Upadhyay Added Task-1
  Open_Source/Task/Priyabrata Upadhyay/README.md
Labels: approved

#144 Completed task-1 --Abhishek Pani
  Open_Source/Task/Abhishek_Pani/README.md
Labels: approved

#147 Open-source task completed
  Open_Source/Task/Suhani_Dalpat/README.md
Labels: approved

#139 Task complete!!
  Open_Source/Task/Ronak Kumar Sahu/README.md
Labels: approved

#114 FIRST_TASK_COMPLETED
  Open_Source/Task/Shubhra_Dash/README.md
Labels: approved

#150 location changed
  Open_Source/Task/prangya/README.md
Labels: approved

#129 COMPLETED TASK 1 SUCCESSFULLY!!
  Open_Source/Task/Aditya Swarup Khuntia/README.md
Labels: approved

#151 task completed
  Open_Source/Task/Gungun Agrawal/README.md
Labels: approved

#145 1st task completed
  Open_Source/Task/Taofique_khan/README.md
Labels: approved

#154 Added Introduction
  Open_Source/Task/Hitanshu_Mahanta/README.md
Labels: approved

#155 Yash Goyal Intro Folder
  Open_Source/Task/yash goyal/README.md
Labels: approved

#158 completed the task
  Open_Source/Task/Niharika/READ.md
Labels: invalid

#157 task completed
  Open_Source/Task/Lisa_Pradhan/README.md
Labels: approved

#160 my task
  Open_Source/Task/Sonalika Dash/README.md
Labels: approved

#181 Added README file
  Open_Source/Task/Aayush_Patro/README.md
Labels: approved

#169 Somesh Behera
  Domain/Web Development/Task/Somesh_Behera/README.md
  Domain/Web Development/Task/Somesh_Behera/Task-1-Desktop.png
  Domain/Web Development/Task/Somesh_Behera/Task-1-Mobile.jpg
  Domain/Web Development/Task/Somesh_Behera/Task-1-Tablet-Landscape.jpg
  Domain/Web Development/Task/Somesh_Behera/Task-1-Tablet-Potrait.jpg
  Domain/Web Development/Task/Somesh_Behera/image-1.png
  Domain/Web Development/Task/Somesh_Behera/index.html
  Domain/Web Development/Task/Somesh_Behera/link.txt
  Domain/Web Development/Task/Somesh_Behera/novel-1.jpg
  Domain/Web Development/Task/Somesh_Behera/novel-2.jpeg
  Domain/Web Development/Task/Somesh_Behera/novel-3.jpeg
  Domain/Web Development/Task/Somesh_Behera/sf-1.jpg
  Domain/Web Development/Task/Somesh_Behera/sf-2.jpg
  Domain/Web Development/Task/Somesh_Behera/sf-3.JPEG
  Domain/Web Development/Task/Somesh_Behera/style.css
Labels: approved, fully responsive

#251 #Task_02
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/The-Fairy-Glitch-Mother-Science-Books-for-Kids-min-1024x768.jpg
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/WEB_link.txt
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/index.html
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/picture-books-for-eyfs-list-l.jpg
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/scienc3.jpg
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/science1.jpg
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/science2.jpg
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/story1.jpeg
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/story1.webp
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/story2.jpg
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/story3.jpeg
  Domain/Web Development/Task/Om_Praksh_Bisoi/Souce_code/style.css
  Domain/Web Development/Task/Om_Praksh_Bisoi/WEB_LINK.txt
Labels: approved, fully responsive

#245 webdev task completed
  Domain/Web Development/Task/GungunAgrawal/Assests/Sc.b-1.jpeg
  Domain/Web Development/Task/GungunAgrawal/Assests/Sc.b-1.jpg
  Domain/Web Development/Task/GungunAgrawal/Assests/Sc.b-2.jpg
  Domain/Web Development/Task/GungunAgrawal/Assests/Sc.b-3.jpg
  Domain/Web Development/Task/GungunAgrawal/Assests/about.jpg
  Domain/Web Development/Task/GungunAgrawal/Assests/herosec-1.jpeg
  Domain/Web Development/Task/GungunAgrawal/Assests/herosec-1.png.jpeg
  Domain/Web Development/Task/GungunAgrawal/Assests/herosec-2.jpeg
  Domain/Web Development/Task/GungunAgrawal/Assests/herosec-2.png
  Domain/Web Development/Task/GungunAgrawal/Assests/st.b-1.jpg
  Domain/Web Development/Task/GungunAgrawal/Assests/st.b-2.jpg
  Domain/Web Development/Task/GungunAgrawal/Assests/st.b-3.jpg
  Domain/Web Development/Task/GungunAgrawal/index.html
  Domain/Web Development/Task/GungunAgrawal/link.txt
  Domain/Web Development/Task/GungunAgrawal/style.css
Labels: approved, fully responsive

#244 Web Dev task completed
  Domain/Web Development/Task/Suhani Dalpat/Assests/Sc.b-1.jpg
  Domain/Web Development/Task/Suhani Dalpat/Assests/Sc.b-2.jpg
  Domain/Web Development/Task/Suhani Dalpat/Assests/Sc.b-3.jpg
  Domain/Web Development/Task/Suhani Dalpat/Assests/about.jpg
  Domain/Web Development/Task/Suhani Dalpat/Assests/book-1283865_1280.jpg
  Domain/Web Development/Task/Suhani Dalpat/Assests/herosec-1.png
  Domain/Web Development/Task/Suhani Dalpat/Assests/herosec-2.png
  Domain/Web Development/Task/Suhani Dalpat/Assests/st.b-1.jpg
  Domain/Web Development/Task/Suhani Dalpat/Assests/st.b-2.jpg
  Domain/Web Development/Task/Suhani Dalpat/Assests/st.b-3.jpg
  Domain/Web Development/Task/Suhani Dalpat/index.html
  Domain/Web Development/Task/Suhani Dalpat/link.txt
  Domain/Web Development/Task/Suhani Dalpat/style.css
Labels: approved, fully responsive

#240 web dev task completed
  Domain/Web Development/Task/biswajit/index.html
  Domain/Web Development/Task/biswajit/link.txt
Labels: awesome, approved, fully responsive

#236 web dev task completed
  Domain/Web Development/Task/gouravKJ/index.html
  Domain/Web Development/Task/gouravKJ/link.txt
  Domain/Web Development/Task/gouravKJ/style.css
Labels: awesome, approved, fully responsive

#232 Website created
  Domain/Web Development/Task/Simahdri_Yaswant/7125+5E40JL._AC_UF1000,1000_QL80_.jpg
  Domain/Web Development/Task/Simahdri_Yaswant/91kkk-xBuOL.jpg
  Domain/Web Development/Task/Simahdri_Yaswant/91uMrXq+4RL.jpg
  Domain/Web Development/Task/Simahdri_Yaswant/ChatGPT Image Apr 12, 2025, 03_53_03 PM.png
  Domain/Web Development/Task/Simahdri_Yaswant/adventures-of-sherlock-holmes-original-imaezt8fjxcuujhd.webp
  Domain/Web Development/Task/Simahdri_Yaswant/index.html
  Domain/Web Development/Task/Simahdri_Yaswant/lech1cc.jpg
  Domain/Web Development/Task/Simahdri_Yaswant/leph2cc.jpg
  Domain/Web Development/Task/Simahdri_Yaswant/link.txt
  Domain/Web Development/Task/Simahdri_Yaswant/styles.css
Labels: awesome, approved, fully responsive

#231 web dev task added
  Domain/Web Development/Task/Aditi/alchemist.jpg
  Domain/Web Development/Task/Aditi/background.jpg
  Domain/Web Development/Task/Aditi/book-cover-To-Kill-a-Mockingbird-many-.webp
  Domain/Web Development/Task/Aditi/books
  Domain/Web Development/Task/Aditi/children reading book.avif
  Domain/Web Development/Task/Aditi/graduation+ book.jpg
  Domain/Web Development/Task/Aditi/harry potter.jpg
  Domain/Web Development/Task/Aditi/index.html
  Domain/Web Development/Task/Aditi/link.txt
  Domain/Web Development/Task/Aditi/network science.jpg
  Domain/Web Development/Task/Aditi/opaque pic.png
  Domain/Web Development/Task/Aditi/style.css
  Domain/Web Development/Task/Aditi/the eleganty universe.jpg
  Domain/Web Development/Task/Aditi/the palace of illusion.jpg
  Domain/Web Development/Task/Aditi/the science of science.jpg
Labels: approved, fully responsive

#230 Web Dev task completed
  Domain/Web Development/Task/Rudrakant_Sahoo/book 2.jpg
  Domain/Web Development/Task/Rudrakant_Sahoo/book 6.jpg
  Domain/Web Development/Task/Rudrakant_Sahoo/book1.jpg
  Domain/Web Development/Task/Rudrakant_Sahoo/book3.avif
  Domain/Web Development/Task/Rudrakant_Sahoo/book4.webp
  Domain/Web Development/Task/Rudrakant_Sahoo/book5.jpg
  Domain/Web Development/Task/Rudrakant_Sahoo/book7.png
  Domain/Web Development/Task/Rudrakant_Sahoo/book8.jpg
  Domain/Web Development/Task/Rudrakant_Sahoo/books7.jpg
  Domain/Web Development/Task/Rudrakant_Sahoo/bookshero.jpg
  Domain/Web Development/Task/Rudrakant_Sahoo/index.html
  Domain/Web Development/Task/Rudrakant_Sahoo/link.txt
  Domain/Web Development/Task/Rudrakant_Sahoo/style.css
Labels: approved, fully responsive

#229 WEB DEV Task Completed
  Domain/Web Development/Task/harsha/index.html
  Domain/Web Development/Task/harsha/link.txt
  Domain/Web Development/Task/index.html
  Domain/Web Development/Task/link.txt
Labels: awesome, approved, fully responsive

#225 WEB DEVELOPMENT TASK COMPLETED
  Domain/Web Development/Task/SoumyaRanjanBhol/business1.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/business2.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/business3.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/business4.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/child.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/education1.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/education2.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/education3.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/education4.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/index.html
  Domain/Web Development/Task/SoumyaRanjanBhol/link.txt
  Domain/Web Development/Task/SoumyaRanjanBhol/novel1.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/novel2.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/novel3.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/novel4.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/science1.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/science2.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/science3.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/science4.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/story1.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/story2.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/story3.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/story4.jpg
  Domain/Web Development/Task/SoumyaRanjanBhol/style.css
Labels: awesome, approved, fully responsive

#223 web task done
  Domain/Web Development/Task/swagatika/copper.html
  Domain/Web Development/Task/swagatika/coppers.css
  Domain/Web Development/Task/swagatika/link.txt
Labels: awesome, approved, fully responsive

#221 Subha's The Hidden Shelf
  Domain/Web Development/Task/Subha Sourabha Sahu/images/BK 6.jpg
  Domain/Web Development/Task/Subha Sourabha Sahu/images/bk -1.jpg
  Domain/Web Development/Task/Subha Sourabha Sahu/images/bk -13.jpg
  Domain/Web Development/Task/Subha Sourabha Sahu/images/bk -2.jpg
  Domain/Web Development/Task/Subha Sourabha Sahu/images/bk -3.jpg
  Domain/Web Development/Task/Subha Sourabha Sahu/images/bk -4.jpg
  Domain/Web Development/Task/Subha Sourabha Sahu/images/bk 1.jpg
  Domain/Web Development/Task/Subha Sourabha Sahu/images/bk 3.jpg
  Domain/Web Development/Task/Subha Sourabha Sahu/images/bk 4.jpg
  Domain/Web Development/Task/Subha Sourabha Sahu/images/image 2.jpg
  Domain/Web Development/Task/Subha Sourabha Sahu/images/soon1.jpg
  Domain/Web Development/Task/Subha Sourabha Sahu/index.html
  Domain/Web Development/Task/Subha Sourabha Sahu/style.css
  Domain/Web Development/Task/Subha Sourabha Sahu/subha.txt
Labels: awesome, approved, fully responsive

#219 WEB DEV TASK COMPLETED
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/LINK.TXT
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/New folder/download (1).jpeg
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/New folder/download (2).jpeg
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/New folder/download (3).jpeg
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/New folder/download (4).jpeg
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/New folder/download (5).jpeg
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/New folder/download (6).jpeg
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/New folder/download (7).jpeg
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/New folder/download (8).jpeg
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/New folder/download.jpeg
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/New folder/download.png
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/index.html
  Domain/Web Development/Task/SAMPARK SAGAR BARIK/style.css
Labels: approved, fully responsive

#218 Web Dev task Completed !!
  Domain/Web Development/Task/Rounak_Senapati/Assests/Sc.b-1.jpg
  Domain/Web Development/Task/Rounak_Senapati/Assests/Sc.b-2.jpg
  Domain/Web Development/Task/Rounak_Senapati/Assests/Sc.b-3.jpg
  Domain/Web Development/Task/Rounak_Senapati/Assests/about.jpg
  Domain/Web Development/Task/Rounak_Senapati/Assests/herosec-1.png
  Domain/Web Development/Task/Rounak_Senapati/Assests/herosec-2.png
  Domain/Web Development/Task/Rounak_Senapati/Assests/st.b-1.jpg
  Domain/Web Development/Task/Rounak_Senapati/Assests/st.b-2.jpg
  Domain/Web Development/Task/Rounak_Senapati/Assests/st.b-3.jpg
  Domain/Web Development/Task/Rounak_Senapati/Induction-2025.code-workspace
  Domain/Web Development/Task/Rounak_Senapati/index.html
  Domain/Web Development/Task/Rounak_Senapati/link.txt
  Domain/Web Development/Task/Rounak_Senapati/style.css
Labels: awesome, approved, fully responsive

#213 Web Dev Task Completed.
  Domain/Web Development/Task/Piyush Mishra/README.md
  Domain/Web Development/Task/Piyush Mishra/Sciencebooks.html
  Domain/Web Development/Task/Piyush Mishra/Storybooks.html
  Domain/Web Development/Task/Piyush Mishra/index.html
  Domain/Web Development/Task/Piyush Mishra/link.txt.txt
  Domain/Web Development/Task/Piyush Mishra/style.css
Labels: approved

#212 completed domain task
  Domain/Web Development/Task/Debasmita_raut_WebTask1/201610825.jpg
  Domain/Web Development/Task/Debasmita_raut_WebTask1/718-Up30r+L._AC_UF1000,1000_QL80_.jpg
  Domain/Web Development/Task/Debasmita_raut_WebTask1/71h+cZ8fSBL._AC_UF1000,1000_QL80_.jpg
  Domain/Web Development/Task/Debasmita_raut_WebTask1/91ZCU63G3QL._UF1000,1000_QL80_.jpg
  Domain/Web Development/Task/Debasmita_raut_WebTask1/9789390183524 (1).webp
  Domain/Web Development/Task/Debasmita_raut_WebTask1/9789390183524.webp
  Domain/Web Development/Task/Debasmita_raut_WebTask1/images.jpeg
  Domain/Web Development/Task/Debasmita_raut_WebTask1/index.html
  Domain/Web Development/Task/Debasmita_raut_WebTask1/link.txt.txt
  Domain/Web Development/Task/Debasmita_raut_WebTask1/styles.css
Labels: awesome, approved, fully responsive

#211 Web dev task by Subhashree Sahu
  Domain/Web Development/Task/Subhashree Sahu/bg2.png
  Domain/Web Development/Task/Subhashree Sahu/index.html
  Domain/Web Development/Task/Subhashree Sahu/link.txt
  Domain/Web Development/Task/Subhashree Sahu/styles.css
Labels: awesome, approved, fully responsive

#209 Domain Task Completed
  Domain/Web Development/Task/Prateek_Kumar_Hota/book1.jpg
  Domain/Web Development/Task/Prateek_Kumar_Hota/book2.jpg
  Domain/Web Development/Task/Prateek_Kumar_Hota/book3.jpg
  Domain/Web Development/Task/Prateek_Kumar_Hota/book4.jpg
  Domain/Web Development/Task/Prateek_Kumar_Hota/book5.jpg
  Domain/Web Development/Task/Prateek_Kumar_Hota/book6.jpg
  Domain/Web Development/Task/Prateek_Kumar_Hota/book7.jpg
  Domain/Web Development/Task/Prateek_Kumar_Hota/book8.jpg
  Domain/Web Development/Task/Prateek_Kumar_Hota/book9.jpg
  Domain/Web Development/Task/Prateek_Kumar_Hota/index.html
  Domain/Web Development/Task/Prateek_Kumar_Hota/link.txt
  Domain/Web Development/Task/Prateek_Kumar_Hota/style.css
Labels: awesome, approved, fully responsive

#208 assignment done : Abhigyan
  Domain/Web Development/Task/Abhigyan-Padhee/assets/bookshelf.jpg
  Domain/Web Development/Task/Abhigyan-Padhee/assets/science.jpeg
  Domain/Web Development/Task/Abhigyan-Padhee/assets/sciennce bookie.jpg
  Domain/Web Development/Task/Abhigyan-Padhee/assets/scienvce.jpg
  Domain/Web Development/Task/Abhigyan-Padhee/assets/storybook.jpg
  Domain/Web Development/Task/Abhigyan-Padhee/assets/storybook4.jpeg
  Domain/Web Development/Task/Abhigyan-Padhee/assets/storybookie.jpg
  Domain/Web Development/Task/Abhigyan-Padhee/index.html
  Domain/Web Development/Task/Abhigyan-Padhee/link.txt
  Domain/Web Development/Task/Abhigyan-Padhee/style.css
Labels: approved, fully responsive

#207 Aryan Rajguru - Readers Hub
  Domain/Web Development/Task/AryanRajguru/aryan.txt
  Domain/Web Development/Task/AryanRajguru/images/b1.jpg
  Domain/Web Development/Task/AryanRajguru/images/banner.png
  Domain/Web Development/Task/AryanRajguru/images/bs1.jpg
  Domain/Web Development/Task/AryanRajguru/images/bs2.jpg
  Domain/Web Development/Task/AryanRajguru/images/bs3.jpg
  Domain/Web Development/Task/AryanRajguru/images/bs4.jpg
  Domain/Web Development/Task/AryanRajguru/images/bs5.jpg
  Domain/Web Development/Task/AryanRajguru/images/bs6.jpg
  Domain/Web Development/Task/AryanRajguru/images/logo.png
  Domain/Web Development/Task/AryanRajguru/images/logo1.png
  Domain/Web Development/Task/AryanRajguru/images/sb1.webp
  Domain/Web Development/Task/AryanRajguru/images/sb2.jpg
  Domain/Web Development/Task/AryanRajguru/images/sb3.png
  Domain/Web Development/Task/AryanRajguru/images/sb4.png
  Domain/Web Development/Task/AryanRajguru/images/sc1.webp
  Domain/Web Development/Task/AryanRajguru/images/sc2.webp
  Domain/Web Development/Task/AryanRajguru/images/sc3.webp
  Domain/Web Development/Task/AryanRajguru/images/sc4.webp
  Domain/Web Development/Task/AryanRajguru/index.html
  Domain/Web Development/Task/AryanRajguru/science.css
  Domain/Web Development/Task/AryanRajguru/science.html
  Domain/Web Development/Task/AryanRajguru/story.html
  Domain/Web Development/Task/AryanRajguru/style.css
Labels: approved, fully responsive

#205 Web Dev Task Completed
  Domain/Web Development/Task/Snehanshu_Kar/Link.txt
  Domain/Web Development/Task/Snehanshu_Kar/book1.jpeg
  Domain/Web Development/Task/Snehanshu_Kar/book2.jpg
  Domain/Web Development/Task/Snehanshu_Kar/book3.jpeg
  Domain/Web Development/Task/Snehanshu_Kar/books.css
  Domain/Web Development/Task/Snehanshu_Kar/chaosscience1.jpeg
  Domain/Web Development/Task/Snehanshu_Kar/granddesignscience3.jpg
  Domain/Web Development/Task/Snehanshu_Kar/index.html
  Domain/Web Development/Task/Snehanshu_Kar/quantumscience2.jpg
Labels: approved, fully responsive

#204 Saswat Mohanty (GOT BookStore)
  Domain/Web Development/Task/SASWATMOHANTY/Saswat.txt
  Domain/Web Development/Task/SASWATMOHANTY/gotnew.css
  Domain/Web Development/Task/SASWATMOHANTY/index.html
Labels: awesome, approved, fully responsive

#201 web task
  Domain/Web Development/Task/natashasahu/index.html
  Domain/Web Development/Task/natashasahu/link.txt
  Domain/Web Development/Task/natashasahu/style.css
Labels: approved, fully responsive

#200 Web Dev task done
  Domain/Web Development/Task/Sambhav_Shadangi/Images/BookCover1.jpg
  Domain/Web Development/Task/Sambhav_Shadangi/Images/BookCover2.jpg
  Domain/Web Development/Task/Sambhav_Shadangi/Images/BookCover3.webp
  Domain/Web Development/Task/Sambhav_Shadangi/Images/Chemistry.jpg
  Domain/Web Development/Task/Sambhav_Shadangi/Images/Mathematics.jpg
  Domain/Web Development/Task/Sambhav_Shadangi/Images/Physics.jpg
  Domain/Web Development/Task/Sambhav_Shadangi/Images/SHELF STORIES WELCOME’S YOU.png
  Domain/Web Development/Task/Sambhav_Shadangi/Images/banner.jpg
  Domain/Web Development/Task/Sambhav_Shadangi/Images/banner3.jpg
  Domain/Web Development/Task/Sambhav_Shadangi/Images/banner_resized.jpg
  Domain/Web Development/Task/Sambhav_Shadangi/Images/wmremove-transformed.jpg
  Domain/Web Development/Task/Sambhav_Shadangi/index.html
  Domain/Web Development/Task/Sambhav_Shadangi/link.txt
  Domain/Web Development/Task/Sambhav_Shadangi/style.css
Labels: awesome, approved, fully responsive

#198 web task
  Domain/Web Development/Task/namitanaik/index.html
  Domain/Web Development/Task/namitanaik/link.txt
  Domain/Web Development/Task/namitanaik/style.css
Labels: approved, fully responsive

#195 Done by : Debasish Muduli
  Domain/Web Development/Task/Debasish Muduli/assets/book 1.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 10
  Domain/Web Development/Task/Debasish Muduli/assets/book 11.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 12.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 13.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 14.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 2.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 2d.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 3.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 4.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 5.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 6.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 7.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 8.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/book 9.jpg
  Domain/Web Development/Task/Debasish Muduli/assets/home-img.jpg
  Domain/Web Development/Task/Debasish Muduli/index.html
  Domain/Web Development/Task/Debasish Muduli/link.txt
  Domain/Web Development/Task/Debasish Muduli/style.css
Labels: approved, fully responsive

#194 completed the task
  Domain/Web Development/Task/PratikBehera/index.html
  Domain/Web Development/Task/PratikBehera/pratik.txt
  Domain/Web Development/Task/PratikBehera/styles.css
Labels: approved, fully responsive

#192 Web Developement Task Completed
  Domain/Web Development/Task/Shruti/image/science1.jpeg
  Domain/Web Development/Task/Shruti/image/science2.jpeg
  Domain/Web Development/Task/Shruti/image/story1.jpeg
  Domain/Web Development/Task/Shruti/image/story2.jpeg
  Domain/Web Development/Task/Shruti/index.html
  Domain/Web Development/Task/Shruti/link.txt
  Domain/Web Development/Task/Shruti/style.css
Labels: approved, fully responsive

#189 web task by ankita
  Domain/Web Development/Task/ankitanaik/Evidence-cover.webp
  Domain/Web Development/Task/ankitanaik/MyAntarctica-cover.webp
  Domain/Web Development/Task/ankitanaik/TheIguanodonsHorn-cover.webp
  Domain/Web Development/Task/ankitanaik/TheNoisyPuddle-cover.webp
  Domain/Web Development/Task/ankitanaik/TheObservologist-cover - Copy.webp
  Domain/Web Development/Task/ankitanaik/anne.jpeg
  Domain/Web Development/Task/ankitanaik/bookcover.avif
  Domain/Web Development/Task/ankitanaik/caps.jpeg
  Domain/Web Development/Task/ankitanaik/charlotte.jpeg
  Domain/Web Development/Task/ankitanaik/harry.jpeg
  Domain/Web Development/Task/ankitanaik/index.html
  Domain/Web Development/Task/ankitanaik/link.txt
  Domain/Web Development/Task/ankitanaik/ruskin.jpeg
  Domain/Web Development/Task/ankitanaik/style.css
Labels: awesome, approved, fully responsive

#186 Web Dev task completed
  Domain/Web Development/Task/SwagatSM/index.html
  Domain/Web Development/Task/SwagatSM/link.txt
  Domain/Web Development/Task/SwagatSM/style.css
Labels: awesome, approved, fully responsive

#185 new
  Domain/Web Development/Task/subham_kumar_rana/clone.html
  Domain/Web Development/Task/subham_kumar_rana/heading.html
  Domain/Web Development/Task/subham_kumar_rana/images.jpeg
  Domain/Web Development/Task/subham_kumar_rana/link.txt.txt
  Domain/Web Development/Task/subham_kumar_rana/sc1.jpeg
  Domain/Web Development/Task/subham_kumar_rana/sc2.jpeg
  Domain/Web Development/Task/subham_kumar_rana/sc3.jpeg
  Domain/Web Development/Task/subham_kumar_rana/st1.jpeg
  Domain/Web Development/Task/subham_kumar_rana/st2.jpeg
  Domain/Web Development/Task/subham_kumar_rana/st3.jpeg
  Domain/Web Development/Task/subham_kumar_rana/style.css
Labels: approved

#184 Web Development Task completed
  Domain/Web Development/Task/Anushree-Mohanty/images/background.jpg
  Domain/Web Development/Task/Anushree-Mohanty/images/hero1.jpg
  Domain/Web Development/Task/Anushree-Mohanty/images/science1.jpg
  Domain/Web Development/Task/Anushree-Mohanty/images/science2.jpg
  Domain/Web Development/Task/Anushree-Mohanty/images/science3.jpg
  Domain/Web Development/Task/Anushree-Mohanty/images/story1.jpg
  Domain/Web Development/Task/Anushree-Mohanty/images/story2.jpg
  Domain/Web Development/Task/Anushree-Mohanty/images/story3.jpg
  Domain/Web Development/Task/Anushree-Mohanty/index.html
  Domain/Web Development/Task/Anushree-Mohanty/link.txt
  Domain/Web Development/Task/Anushree-Mohanty/styles.css
Labels: approved, fully responsive

#182 Domain Wise Task completed
  Domain/Web Development/Task/SameerRaja/images/C1.jpg
  Domain/Web Development/Task/SameerRaja/images/C2.jpg
  Domain/Web Development/Task/SameerRaja/images/C4.jpg
  Domain/Web Development/Task/SameerRaja/images/S1.jpg
  Domain/Web Development/Task/SameerRaja/images/S2.jpg
  Domain/Web Development/Task/SameerRaja/images/S3.jpg
  Domain/Web Development/Task/SameerRaja/images/S4.jpg
  Domain/Web Development/Task/SameerRaja/images/logo1.jpg
  Domain/Web Development/Task/SameerRaja/images/menu.svg
  Domain/Web Development/Task/SameerRaja/index.html
  Domain/Web Development/Task/SameerRaja/link.txt
  Domain/Web Development/Task/SameerRaja/style.css
Labels: approved, fully responsive

#180 WebDev Task Completed Successfully
  Domain/Web Development/Task/Satyajit_Swain/713eFPO6JjL._AC_UF1000,1000_QL80_.jpg
  Domain/Web Development/Task/Satyajit_Swain/71TJOtt2AML._AC_UF1000,1000_QL80_.jpg
  Domain/Web Development/Task/Satyajit_Swain/71rrPVH-xFL._AC_UF1000,1000_QL80_.jpg
  Domain/Web Development/Task/Satyajit_Swain/91dSMhdIzTL.jpg
  Domain/Web Development/Task/Satyajit_Swain/about_us.html
  Domain/Web Development/Task/Satyajit_Swain/content.png
  Domain/Web Development/Task/Satyajit_Swain/home.html
  Domain/Web Development/Task/Satyajit_Swain/index.html
  Domain/Web Development/Task/Satyajit_Swain/link.txt
  Domain/Web Development/Task/Satyajit_Swain/science.html
  Domain/Web Development/Task/Satyajit_Swain/story.html
  Domain/Web Development/Task/Satyajit_Swain/test.css
Labels: approved

#179 Web dev task completed
  Domain/Web Development/Task/Sudeepa_Badatya/blackhole.jpg
  Domain/Web Development/Task/Sudeepa_Badatya/book1.png
  Domain/Web Development/Task/Sudeepa_Badatya/index.html
  Domain/Web Development/Task/Sudeepa_Badatya/link.txt
  Domain/Web Development/Task/Sudeepa_Badatya/style.css
Labels: approved, fully responsive

#178 Task completed BY Madhu Sailesh Sasamal
  Domain/Web Development/Task/Madhu_Sailesh_Sasamal/README.md
  Domain/Web Development/Task/Madhu_Sailesh_Sasamal/img/BACKGROUND.png
  Domain/Web Development/Task/Madhu_Sailesh_Sasamal/img/BOOKpic.png
  Domain/Web Development/Task/Madhu_Sailesh_Sasamal/img/Midnight Dreams.png
  Domain/Web Development/Task/Madhu_Sailesh_Sasamal/img/THE lost Kingdom.png
  Domain/Web Development/Task/Madhu_Sailesh_Sasamal/img/The Amazing Chronicles of Science.png
  Domain/Web Development/Task/Madhu_Sailesh_Sasamal/img/fundamentalphy.png
  Domain/Web Development/Task/Madhu_Sailesh_Sasamal/index.html
  Domain/Web Development/Task/Madhu_Sailesh_Sasamal/link.txt
  Domain/Web Development/Task/Madhu_Sailesh_Sasamal/style.css
Labels: approved, fully responsive

#177 Web Task Done, By T Prem
  Domain/Web Development/Task/T Prem/Assets/SB1.jpg
  Domain/Web Development/Task/T Prem/Assets/SB2.jpg
  Domain/Web Development/Task/T Prem/Assets/SB3.jpg
  Domain/Web Development/Task/T Prem/Assets/SB4.jpg
  Domain/Web Development/Task/T Prem/Assets/STB1.jpg
  Domain/Web Development/Task/T Prem/Assets/STB2.jpg
  Domain/Web Development/Task/T Prem/Assets/STB3.jpg
  Domain/Web Development/Task/T Prem/Assets/STB4.jpg
  Domain/Web Development/Task/T Prem/Assets/bg.jpg
  Domain/Web Development/Task/T Prem/Portfolio_link.txt
  Domain/Web Development/Task/T Prem/README.md
  Domain/Web Development/Task/T Prem/index.html
  Domain/Web Development/Task/T Prem/link.txt
  Domain/Web Development/Task/T Prem/style.css
Labels: approved, fully responsive

#176 Domain_Task1
  Domain/Web Development/Task/Vysyaraju_Hansuja/image.png
  Domain/Web Development/Task/Vysyaraju_Hansuja/image1.png
  Domain/Web Development/Task/Vysyaraju_Hansuja/image2.png
  Domain/Web Development/Task/Vysyaraju_Hansuja/image3.jpg
  Domain/Web Development/Task/Vysyaraju_Hansuja/image4.png
  Domain/Web Development/Task/Vysyaraju_Hansuja/image5.jpg
  Domain/Web Development/Task/Vysyaraju_Hansuja/image6.png
  Domain/Web Development/Task/Vysyaraju_Hansuja/index .html
  Domain/Web Development/Task/Vysyaraju_Hansuja/link.txt
  Domain/Web Development/Task/Vysyaraju_Hansuja/style.css
  Domain/Web Development/Task/Vysyaraju_Hansuja/vercel.json
Labels: approved, fully responsive

#173 Web Dev Task Submission - Aurodeepa
  Domain/Web Development/Task/Aurodeepa/about-icon.png
  Domain/Web Development/Task/Aurodeepa/contact-icon.png
  Domain/Web Development/Task/Aurodeepa/home-icon.png
  Domain/Web Development/Task/Aurodeepa/index.html
  Domain/Web Development/Task/Aurodeepa/instagram1.png
  Domain/Web Development/Task/Aurodeepa/instagram2.png
  Domain/Web Development/Task/Aurodeepa/link.txt
  Domain/Web Development/Task/Aurodeepa/science-icon.png
  Domain/Web Development/Task/Aurodeepa/science1.jpg
  Domain/Web Development/Task/Aurodeepa/science2.jpg
  Domain/Web Development/Task/Aurodeepa/story-icon.png
  Domain/Web Development/Task/Aurodeepa/story1.jpg
  Domain/Web Development/Task/Aurodeepa/story2.jpg
  Domain/Web Development/Task/Aurodeepa/style.css
  Domain/Web Development/Task/Aurodeepa/twitter.png
  Domain/Web Development/Task/Aurodeepa/twitter1.png
Labels: approved
